export const MODAL_TYPES = {
    LOCAL_STAGING_API_REQUEST_WARN: 'LOCAL_STAGING_API_REQUEST_WARN',
    LOCAL_STAGING_RETAILER_SWITCH_WARN: 'LOCAL_STAGING_RETAILER_SWITCH_WARN',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    CUSTOMER_SUBSIDIARIES_WARN: 'CUSTOMER_SUBSIDIARIES_WARN',
};
